### PR TITLE
fix typos in README.md

### PR DESCRIPTION
**Pull request by Suban05**
Fixed typos in README.md

### CODE REVIEW

**Comment by bibendi** [comment]
Thank you!

**Comment by JiantaoHe** [comment]
Hi @bibendi, I'm trying to follow the read-me to start the processors, but what's the full command?
I only see there are parameters, but how do I run them?

image

**Comment by JiantaoHe** [comment]
Oh, thank you very much

**Comment by JiantaoHe** [comment]
Sorry I'm still not able to process the outbox item, here is my code screenshots, any issues?
image
image
image

**Comment by bibendi** [comment]
It's hard to say. Could you provide a minimal representation app?

**Comment by JiantaoHe** [comment]
hmm... I debugged the code and found it raised exception on 
/lib/sbmt/outbox/v2/processor.rb:75
`undefined method `ids' for an instance of Sbmt::Outbox::V2::Tasks::Base`
the task doesn't have ids method, do you have any insight?

**Comment by JiantaoHe** [comment]
one quick question: why I cann't see any log in my console? I saw there are loggers in the code but nothing in my console

**Pull request merged**
